# Generated by Django 4.2.4 on 2023-08-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.IntegerField()),
                ('base', models.IntegerField()),
                ('downwind', models.IntegerField()),
                ('initial', models.IntegerField()),
                ('drop', models.IntegerField()),
                ('vertical_speed', models.IntegerField()),
                ('glide_ratio', models.FloatField()),
                ('swoop', models.IntegerField()),
                ('landing_dir', models.IntegerField()),
                ('pattern_dir', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('pattern', models.ImageField(upload_to='patterns')),
            ],
        ),
    ]
