# Generated by Django 4.2.4 on 2023-08-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_alter_plan_landing_dir_alter_plan_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='final_drop',
            field=models.IntegerField(default=140),
            preserve_default=False,
        ),
    ]
